"""Constants for HA Performance Diagnostics."""

from homeassistant.const import Platform

DOMAIN = "ha_performance_diagnostics"
PLATFORMS = [Platform.SENSOR]

# Config keys
CONF_SCAN_INTERVAL = "scan_interval"
CONF_SLOW_QUERY_THRESHOLD = "slow_query_threshold_ms"
CONF_STATE_CHANGE_THRESHOLD = "state_change_threshold"
CONF_DB_SIZE_WARN_MB = "db_size_warn_mb"

# Defaults
DEFAULT_SCAN_INTERVAL = 300
DEFAULT_SLOW_QUERY_THRESHOLD_MS = 500
DEFAULT_STATE_CHANGE_THRESHOLD = 60
DEFAULT_DB_SIZE_WARN_MB = 1000

# Health score deduction constants
HEALTH_CPU_HIGH = 50
HEALTH_CPU_MEDIUM = 30
HEALTH_CPU_HIGH_DEDUCTION = 20
HEALTH_CPU_MEDIUM_DEDUCTION = 10
HEALTH_DB_HIGH_DEDUCTION = 20
HEALTH_DB_MEDIUM_DEDUCTION = 10
HEALTH_DB_MEDIUM_FACTOR = 0.75
HEALTH_NOISY_ENTITY_DEDUCTION = 15
HEALTH_RECORDER_QUEUE_THRESHOLD = 500
HEALTH_RECORDER_QUEUE_DEDUCTION = 10
HEALTH_SLOW_INTEGRATION_THRESHOLD = 1000
HEALTH_SLOW_INTEGRATION_DEDUCTION = 10
HEALTH_ANTIPATTERN_DEDUCTION = 5

# Data keys
DATA_SYSTEM = "system"
DATA_DB = "db"
DATA_STATE_CHANGES = "state_changes"
DATA_INTEGRATIONS = "integrations"
DATA_ANTIPATTERNS = "antipatterns"
DATA_HEALTH_SCORE = "health_score"
DATA_RECOMMENDATIONS = "recommendations"
